spring:
  application:
    name: sentinel-demo-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      web-context-unify: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9000